kind: pipeline
type: docker
name: memo-server

steps:
  - name: maven build
    image: maven:3.9.1-sapmachine-17
    volumes:
      - name: maven-repo
        path: /root/.m2
    commands:
      - mvn -DskipTests=true clean package

  - name: docker build
    image: plugins/docker
    settings:
      registry: web.kingwrcy.cn:47382
      repo: kingwrcy/memo-server
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password




volumes:
  - name: maven-repo
    host:
      path: /var/lib/maven-repo