kind: pipeline
type: docker
name: memo-server
trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: maven build
    image: maven:3.9.1-sapmachine-17
    volumes:
      - name: maven-repo
        path: /root/.m2
    commands:
      - mvn -DskipTests=true clean package

  - name: docker build
    image: plugins/docker
    settings:
      registry: http://192.168.2.33:47382
      repo: 192.168.2.33:47382/kingwrcy/memo-server
      tags: latest
      cache_from: 192.168.2.33:47382/kingwrcy/memo-server:latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: start service
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.2.33
      username: root
      key:
        from_secret: ds920_private_key
      port: 22
      command_timeout: 2m
      script:
        - cd /volume1/docker/drone/memo-server/
        - chmod +x ./startup.sh
        - ./startup.sh

volumes:
  - name: maven-repo
    host:
      path: /var/lib/maven-repo